### ISSUE TITLE
Error parsing IPython 3.0.0 notebook

### ISSUE THREAD

**Issue by rlabbe** [bobjansen/ipy_pep8#4]
When trying to parse the files in [this repository](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python) I get an exception KeyError: 'worksheets'  in the function get_code_cells(). 

The notebook format changed with version 3; I do not believe that 'worksheets' is used any more. The new format is documented [here](http://ipython.org/ipython-doc/3/notebook/nbformat.html#metadata)

If you don't have time to work on this I might be able to submit a pull request; I've worked with the new notebook formats a bit.

**Comment by bobjansen** [comment]
A pull request is of course much appreciated but I will have time tonight (in 12 hours) to work on this. It seems to be fixable quite easily so if you're not in a hurry I can pick it up.

**Comment by rlabbe** [comment]
I'm in no hurry, thanks!

**Comment by bobjansen** [comment]
Your issue should be fixed now but when I ran the tool on your files an encoding issue popped up. I will fix that next.
